{{- if and .Values.secretEnv (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ladderframe.fullname" . }}
  labels: {{- include "ladderframe.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $name, $value := .Values.secretEnv }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
{{- end }}
