"""`ladderframe cron`: combine `etc/cron.d/*` into one crontab and exec supercronic on it.

supercronic reads a single crontab, so share/ and root files are concatenated (a root file with the
same name replaces the shared one) into `<root>/var/run/crontab`. Jobs run with the agent root as
the working directory and `AGENT_ROOT` set, so a job line can be:

    0 7 * * *  ladderframe run "Write the daily report into var/log/daily.md"
"""

from __future__ import annotations

import os
import shutil
from pathlib import Path

from ..core.rootfs import AgentRoot, Layer


def build_crontab(root: AgentRoot, share: Layer | None) -> Path:
    files: dict[str, Path] = {}
    for layer in (share, root):
        if layer and layer.cron_d.is_dir():
            for path in layer.cron_d.iterdir():
                if path.is_file() and not path.name.startswith("."):
                    files[path.name] = path
    root.ensure_runtime_dirs()
    target = root.var_run / "crontab"
    parts = ["# generated by ladderframe from etc/cron.d — do not edit\n"]
    for name in sorted(files):
        parts.append(f"# --- {files[name]}\n{files[name].read_text(encoding='utf-8').rstrip()}\n")
    target.write_text("\n".join(parts), encoding="utf-8")
    return target


def exec_supercronic(crontab: Path, root: AgentRoot, extra_args: list[str] | None = None) -> None:
    binary = shutil.which("supercronic")
    if binary is None:
        raise SystemExit("supercronic not found on PATH; run `ladderframe boot` (etc/init.d/01_boot.sh installs it)")
    os.environ["AGENT_ROOT"] = str(root.path)
    os.environ.setdefault("LADDERFRAME_ROOT", str(root.path))
    os.chdir(root.path)
    os.execv(binary, [binary, *(extra_args or []), str(crontab)])
